name: "Configure Nhost's Container Registry"
description: "Configure Nhost's Container Registry"
runs:
  using: "composite"
  steps:
    - run: |
        sudo nhost docker-credentials configure
      shell: bash
